#just for tac
statistics=true
<<<<<<< HEAD
job=SCD_2_with_HashKey
jobVersion=0.1
date=2026-06-13 140704012
contextName=Default
jobId=_ZiKHEFucEfChRZL7JxCgiQ
=======
job=CountFile_job
jobVersion=0.1
date=2026-06-13 082751339
contextName=Default
jobId=_aCdUAB55EfGHPrTVeYhjdQ
>>>>>>> 1e4db9de03a9472dab1c7ca4aebd934556b496de
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=