#this is context properties
#Sat Jun 13 19:37:01 IST 2026
host=
username=
password=
port=
database=
ora_schema=
ora_host=
ora_port=
ora_database=
ora_username=
ora_password=
s3_accesskey=
s3_secretkey=
LFS=
sf_account=
sf_user_id=
sf_password=
sf_warehouse=
sf_schema=
sf_database=
s3_putkey=
s3_bucket=
key_folder_part=
key_file_part=
custom_errorMessage=
custom_errorMessage2=
ContextDir=
ContextFile=
SourceFileDir=
cdateformat=
to_mail=
from_mail=
mail_host=
mail_port=
mail_username=
mail_password=
dir_context=
LFS_for_s3=
LFS_for_logging=
LFS_for_tSchemaReject=
project_name=
LFS_for_Received_data_from_S3=
ftp_user=
ftp_port=
ftp_host=
ftp_password=
LFS_for_logging_2_0=
LFS_2_0=
LFS_for_s3_2_0=
LFS_for_Received_data_from_S3_2_0=
LFS_for_SF_data=
LFS_for_tSchemaReject_2_0=
sf_default_database=
sf_default_schema=
LFS_for_Holding_SF_Data=
s3_putkey_2=
s3_bucket_2=
